const obj = [
  {
    id: "1",
    guid: "3638b433-79dc-1825-495d-549762c8cce6",
    name: { zh: "选项1" },
    rightlabel: "",
    score: "",
    resurl: "",
    restype: "",
    goto: "",
    group: 0,
    userDefinedGroup: "",
    value: "",
    visible: true,
    required: true,
    enabled: true,
    hasinput: false,
    inputtype: "",
    inputrequired: false,
    inputsize: 0,
    inputvalue: "",
    parentId: "",
    order: true,
    visibleDependent: ""
  },
  {
    id: "2",
    guid: "dcaa4cfe-79f3-4627-d9e2-2eb57a441be2",
    name: { zh: "选项2" },
    rightlabel: "",
    score: "",
    resurl: "",
    restype: "",
    goto: "",
    group: 0,
    userDefinedGroup: "",
    value: "",
    visible: true,
    required: true,
    enabled: true,
    hasinput: false,
    inputtype: "",
    inputrequired: false,
    inputsize: 0,
    inputvalue: "",
    parentId: "",
    order: true,
    visibleDependent: ""
  },
  {
    id: "3",
    guid: "1f6c668a-9e69-7956-ec25-28e362043dfd",
    name: { zh: "选项3" },
    rightlabel: "",
    score: "",
    resurl: "",
    restype: "",
    goto: "",
    group: 0,
    userDefinedGroup: "",
    value: "",
    visible: true,
    required: true,
    enabled: true,
    hasinput: false,
    inputtype: "",
    inputrequired: false,
    inputsize: 0,
    inputvalue: "",
    parentId: "",
    order: false,
    visibleDependent: ""
  }
];
obj.sort((a, b) => a.order - b.order);
console.log(10, obj);
